receivers:
  prometheus:
    config:
        scrape_configs:
          - job_name: 'scrape-node-exporter'
            scrape_interval: 5s
            static_configs:
              - targets: ['0.0.0.0:9100']
processors:
  batch:
exporters:
  # Debug exporter
  # If using version 0.85 or lower of the Collector
  # replace 'debug' with 'logging'
  debug:
    verbosity: Detailed
service:
  pipelines:
    metrics:
      receivers: ["prometheus"]
      processors: ["batch"]
      exporters: 
        - "logging"
