name: "otelcol-fips"

on:
  push:
    branches:
      - otelcol-fips

concurrency:
  group: otelcol-fips-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.21.12"

jobs:
  otelcol-fips:
    runs-on: ${{ fromJSON('["ubuntu-20.04", "otel-arm64"]')[matrix.GOARCH == 'arm64'] }}
    strategy:
      matrix:
        include:
          - GOOS: linux
            GOARCH: amd64
          - GOOS: linux
            GOARCH: arm64
          - GOOS: windows
            GOARCH: amd64
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: '**/go.sum'
      - run: make otelcol-fips
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}
      - uses: actions/upload-artifact@v4
        with:
          name: otelcol-fips-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: ./bin/otelcol-fips*
